spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
      lettuce:
        pool:
          enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.tracing.BraveAutoConfiguration

management:
  health:
    redis:
      enabled: false
  tracing:
    brave:
      enabled: false
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}

logging:
  level:
    root: INFO
    com.homegenie: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework: DEBUG
