spring:
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
  data:
    redis:
      connect-timeout: 5000 # Increased timeout for production
      ssl:
        enabled: ${REDIS_SSL:false}
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.tracing.BraveAutoConfiguration

management:
  health:
    redis:
      enabled: false # Disable Redis health check to prevent startup probe failure if Redis is slow to connect
  tracing:
    brave:
      enabled: false
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}

logging:
  level:
    root: INFO
    com.homegenie: INFO
    org.springframework.cloud.gateway: INFO
