spring:
  cloud:
    gcp:
      trace:
        enabled: false
      pubsub:
        enabled: false
      storage:
        enabled: false
      sql:
        enabled: false
management:
  tracing:
    enabled: false
