spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}

logging:
  level:
    root: WARN
    com.homegenie: INFO
